[workspace]
members = [
  "crates/trakkin-mapping",
  "crates/trakkin-provider-sdk",
]
resolver = "3"

[workspace.package]
authors = ["Elias Benbourenane"]
edition = "2024"
homepage = "https://trakkin.dev"
license = "Apache-2.0"
repository = "https://github.com/trakkin/trakkin-contracts"
rust-version = "1.97.1"
version = "0.0.0"
